import type { Question } from '../types';

export const ARCHITECTURE_QUESTIONS: Question[] = [
  {
    id: 'arch-1',
    categoryId: 'architecture',
    title: 'Distributed Transactions: Sagas vs 2PC',
    difficulty: 'Expert',
    tags: ['Microservices', 'Saga', '2PC', 'Eventual Consistency'],
    scenario: 'You are architecting an e-commerce checkout system spanning three microservices: Orders, Payments, and Inventory. Each service has its own isolated database. You must ensure that if a payment fails, the reserved inventory is released.',
    question: 'Compare the Two-Phase Commit (2PC) protocol with the Saga Pattern for this architecture. Explain the difference between Choreography and Orchestration in Sagas, and discuss how you handle lack of isolation (e.g., lost updates, dirty reads) in a Saga.',
    idealAnswer: `### 1. Two-Phase Commit (2PC) vs Saga Pattern
* **2PC (Pessimistic / ACID):** A coordinator asks all participating databases to prepare to commit. If all agree, it sends the final commit. 
  * *Flaws:* It is a **blocking protocol**. Locks are held across all databases for the entire duration of the network calls. It scales poorly, and if the coordinator fails during the commit phase, the system is left in a blocking state. It also violates microservice database autonomy.
* **Saga Pattern (Optimistic / BASE):** A sequence of local transactions. Each service updates its own database and publishes an event/message to trigger the next local transaction. If a step fails, the Saga executes **Compensating Transactions** backward to undo the preceding steps.

### 2. Choreography vs Orchestration
* **Choreography:** Services listen to each other's events and decide what action to take. There is no central brain. Excellent for simple workflows (2-3 services), but becomes a tangled "event hairball" as complexity grows.
* **Orchestration:** A dedicated service (the Saga Orchestrator) explicitly tells each participating service what local transaction to execute via command messages. It maintains the overall state machine. Best for complex, mission-critical workflows.

### 3. Handling the Lack of Isolation in Sagas
Because a Saga commits local transactions immediately, other concurrent requests can see partial states (Dirty Reads). To mitigate this, we apply specific design countermeasures:
* **Semantic Lock:** Set a flag on the record (e.g., \`order_status = PENDING_PAYMENT\`) to prevent other transactions from modifying it until the Saga completes.
* **Commutative Updates:** Design operations so they can be executed in any order (e.g., \`UPDATE inventory SET count = count - 1\` rather than setting absolute values).
* **Pessimistic View:** Reorder the Saga steps so that the most risky down-stream operations (like Payments) happen as early as possible, reducing the window for compensation.`,
    pitfalls: [
      'Assuming compensating transactions are automatically generated by the framework (they must be explicitly coded business logic).',
      'Failing to make compensating transactions **idempotent** (network retries can cause them to execute multiple times).',
      'Ignoring the complexity of read-isolation anomalies in BASE architectures.'
    ],
    followUpQuestions: [
      'How do you guarantee that the local database update and the outgoing Kafka event are published atomically? (Outbox Pattern)',
      'What happens if the Saga Orchestrator crashes mid-workflow?'
    ],
    faangFocus: 'Absolute core requirement for Senior/Staff roles. You must be able to prove you can design systems that survive partial network failures without distributed locking.'
  },
{
    id: 'arch-2',
    categoryId: 'architecture',
    title: 'The Transactional Outbox Pattern',
    difficulty: 'Hard',
    tags: ['Outbox Pattern', 'Kafka', 'Atomicity', 'Microservices'],
    scenario: 'Your microservice needs to update a User entity in a PostgreSQL database and simultaneously publish a "UserCreated" event to a Kafka topic. You notice that during network blips, sometimes the database commits but the Kafka message is lost, or vice versa.',
    question: 'Explain the Dual-Write Problem. How does the Transactional Outbox Pattern solve this? Compare the two primary approaches for relaying messages from the outbox table to the message broker: Polling Publisher vs. Transaction Log Tailing (CDC).',
    idealAnswer: `### 1. The Dual-Write Problem
You cannot achieve distributed atomicity between a relational database and a message broker like Kafka using standard local transactions. If you commit the DB first, the network call to Kafka might fail. If you publish to Kafka first, the DB commit might fail, leaving downstream consumers reacting to phantom data.

### 2. The Transactional Outbox Solution
Instead of publishing directly to Kafka, the service uses a single **local ACID transaction** to:
1. Update the business entities (e.g., \`users\` table).
2. Insert a message record into a dedicated \`outbox\` table within the **same database**.
Because both inserts participate in the same local transaction, they are guaranteed to either both commit or both rollback.

### 3. Relaying Mechanisms: Polling vs CDC
Once the messages are safely in the outbox table, a separate asynchronous process relays them to Kafka.
* **Polling Publisher:** A scheduled background thread runs \`SELECT * FROM outbox WHERE processed = false\`, publishes to Kafka, and then marks them as processed.
  * *Pros:* Simple to implement; no external infrastructure needed.
  * *Cons:* Polling introduces latency; frequent queries stress the database; hard to scale horizontally without cluster locks.
* **Transaction Log Tailing (Change Data Capture - CDC):** Using a tool like **Debezium**, the relay directly monitors the database's internal transaction log (e.g., Postgres WAL). When it detects an insert into the \`outbox\` table, it streams the event directly to Kafka.
  * *Pros:* Extremely low latency; zero performance impact on the database query engine; highly scalable.
  * *Cons:* Requires managing additional infrastructure (Kafka Connect / Debezium).

### 4. Delivery Guarantees
Both approaches provide **At-Least-Once delivery**. Because the relay could crash after publishing to Kafka but before updating the outbox status/offset, downstream consumers must be **idempotent**.`,
    pitfalls: [
      'Believing that wrapping the DB call and Kafka call in a \`@Transactional\` annotation makes them atomic.',
      'Forgetting that the Outbox pattern requires consumers to handle duplicate messages.',
      'Not considering the database cleanup strategy for the outbox table (it will grow infinitely without a cleanup job).'
    ],
    followUpQuestions: [
      'How does Debezium handle schema evolution of the outbox table?',
      'If you use the Polling approach, how do you prevent multiple instances of your service from publishing the same outbox rows?'
    ],
    faangFocus: 'Standard architectural pattern for event-driven systems at scale. Proves you understand the boundaries of ACID transactions and network reliability.'
  },
{
    id: 'arch-3',
    categoryId: 'architecture',
    title: 'Idempotency Key Architecture in Payment APIs',
    difficulty: 'Expert',
    tags: ['Idempotency', 'API Design', 'Payments', 'Distributed Systems'],
    scenario: 'You are designing the core /v1/charges API for a payment gateway. Clients will call this endpoint to charge credit cards. If a client experiences a gateway timeout, they will blindly retry the request.',
    question: 'How do you architect an Idempotency mechanism to ensure a user is never double-charged? Detail the exact lifecycle of an idempotency key, the storage layer you would choose, and how you handle concurrent identical requests arriving at the same time.',
    idealAnswer: `### 1. The Idempotency Lifecycle
To guarantee exactly-once charging, clients must provide a unique \`Idempotency-Key\` header (e.g., a V4 UUID) with every mutation request.

The API gateway/service executes the following lifecycle:
1. **Lookup:** Attempt to fetch the key from the Idempotency Store.
2. **First Seen:** If the key is not present, atomically save the key with a status of \`IN_FLIGHT\` and execute the payment. Once the payment completes, update the key's payload with the final HTTP response and status \`COMPLETED\`.
3. **Seen & Completed:** If the key is found with status \`COMPLETED\`, completely bypass the payment logic and directly return the cached HTTP response.
4. **Seen & In-Flight (Concurrency Control):** If the key is found with status \`IN_FLIGHT\`, it means the client sent a concurrent retry before the original request finished. **Do not execute the payment.** Return an HTTP \`409 Conflict\` or \`425 Too Early\` to force the client to back off.

### 2. Storage Layer Selection
* **Redis:** The ideal choice. We can use Redis's atomic \`SET key value NX EX 86400\` command to simultaneously check if the key exists, set it if it doesn't, and apply a 24-hour expiration (TTL) to prevent infinite storage growth.
* **Relational DB:** Can also be used via a unique constraint on the \`idempotency_key\` column, catching duplicates via \`DataIntegrityViolationException\`.

### 3. Edge Cases & Error Handling
* **Client Errors (4xx):** If the request fails due to a validation error (e.g., invalid card number), we can either not store the key or store it with a \`FAILED\` status, allowing the client to fix the payload and retry with the same key.
* **Server Errors (5xx):** If our internal payment processor fails transiently, we must atomically evict the idempotency key so a subsequent retry can attempt the call again.`,
    pitfalls: [
      'Using the hash of the request payload as the idempotency key (prevents legitimate identical distinct orders).',
      'Failing to handle the \`IN_FLIGHT\` race condition, leading to concurrent execution of the same payment.',
      'Not setting a TTL on the idempotency store, leading to memory exhaustion.'
    ],
    followUpQuestions: [
      'What happens if the Redis instance storing the idempotency keys experiences a failover and loses the latest keys?',
      'How do you ensure the HTTP response cached in Redis doesn\'t violate data privacy laws (e.g., PCI-DSS)?'
    ],
    faangFocus: 'Stripe, Square, and Amazon interviewers love this. It tests your ability to handle real-world distributed edge cases, race conditions, and atomic storage operations.'
  },
{
    id: 'arch-4',
    categoryId: 'architecture',
    title: 'Event Sourcing and CQRS at Scale',
    difficulty: 'Expert',
    tags: ['Event Sourcing', 'CQRS', 'Domain Events', 'Eventual Consistency'],
    scenario: 'You are designing a banking ledger system where every transaction must be auditable, reversible, and queryable in multiple ways. The system must handle 50,000 transactions per second.',
    question: 'Explain the Event Sourcing pattern combined with CQRS. How do you handle event schema evolution over time? What are the trade-offs compared to traditional CRUD?',
    idealAnswer: `### 1. Event Sourcing Fundamentals
  Instead of storing the **current state** of an entity, Event Sourcing stores the **sequence of events** that led to that state.
  * **Traditional CRUD:** \`UPDATE accounts SET balance = 100 WHERE id = 123\`
  * **Event Sourcing:** \`AccountCreated(id=123)\`, \`MoneyDeposited(id=123, amount=50)\`, \`MoneyDeposited(id=123, amount=50)\`
  
  The current state is derived by **replaying** all events.
  
  ### 2. CQRS (Command Query Responsibility Segregation)
  CQRS separates the **write model** (commands) from the **read model** (queries):
  * **Command Side:** Writes events to an append-only event store (e.g., EventStoreDB, Kafka).
  * **Query Side:** Projects events into optimized read models (e.g., Elasticsearch, Redis, PostgreSQL).
  
  ### 3. Event Schema Evolution
  This is the hardest part of Event Sourcing. Strategies include:
  * **Weak Schema:** Events are stored as loosely-typed JSON. New fields are added, old fields are ignored.
  * **Upcasting:** When loading old events, an upcaster transforms them to the new schema on-the-fly.
  * **Versioned Events:** Each event has a version number. The system maintains handlers for all versions.
  * **Event Replacement:** Rarely used, but allows rewriting history (breaks auditability).
  
  ### 4. Trade-offs vs CRUD
  **Pros:**
  * **Complete Audit Trail:** Every change is recorded.
  * **Temporal Queries:** You can reconstruct state at any point in time.
  * **Decoupling:** Events can feed multiple read models without coupling.
  
  **Cons:**
  * **Complexity:** Significantly harder to implement than CRUD.
  * **Eventual Consistency:** Read models lag behind writes.
  * **Storage:** Event stores grow indefinitely (requires snapshotting).
  
  ### 5. Performance at Scale
  To handle 50K TPS:
  * **Partitioning:** Shard events by aggregate ID.
  * **Snapshots:** Periodically snapshot aggregate state to avoid replaying millions of events.
  * **Async Projections:** Use Kafka Streams or Flink to project events into read models asynchronously.`,
    pitfalls: [
      'Storing mutable state in events (events must be immutable facts).',
      'Forgetting to implement snapshotting (replay performance degrades over time).',
      'Over-engineering: Event Sourcing is overkill for simple CRUD use cases.'
    ],
    followUpQuestions: [
      'How do you handle GDPR "right to be forgotten" with immutable events?',
      'What is the difference between Event Sourcing and Event-Driven Architecture?'
    ],
    faangFocus: 'Core pattern at companies like Netflix, Uber, and financial institutions. Tests your ability to design systems with complex auditability and scalability requirements.'
  },
{
    id: 'arch-5',
    categoryId: 'architecture',
    title: 'Idempotency for Payment APIs',
    difficulty: 'Hard',
    tags: ['Idempotency', 'Retries', 'Exactly-Once', 'API Design'],
    scenario: 'A mobile client times out waiting for a payment response and retries. Some customers are charged twice. The network layer already retries automatically on 5xx and timeouts.',
    question: 'Design idempotency for this API. Explain the guarantees, the storage model, and the edge cases most designs get wrong.',
    idealAnswer: `### Why this is unavoidable without design
A client that times out **cannot know** whether the request was processed. Retrying risks a duplicate; not retrying risks a lost payment. There is no client-side fix — the server must make retries safe. This is the practical meaning of "exactly-once is impossible; at-least-once plus idempotency is achievable".

### The mechanism
1. The **client generates** an idempotency key (a UUID) per logical operation — not per HTTP attempt — and sends it in a header. Client generation is essential: a server-generated key cannot survive a lost response.
2. On arrival, the server atomically **inserts** the key into a store with status \`IN_PROGRESS\`, using a unique constraint. If the insert fails, this is a retry.
3. Process the payment and store the **response body and status** against the key.
4. On a retry with the same key, return the **stored response** rather than reprocessing.

### The edge cases that get missed
* **Concurrent retries.** Two attempts can arrive simultaneously. The unique-constraint insert is what serialises them; the loser must either wait briefly and return the stored result, or return **409 Conflict** telling the client to retry. Do **not** simply return success — the first request may still fail.
* **In-progress state.** A key present but unfinished means the original is still running. Returning 200 with no result is wrong. Return 409 with \`Retry-After\`.
* **Key reuse with a different body.** A client bug can reuse a key for a different payment. Store a **hash of the request body** and return 422 on mismatch, rather than silently returning the wrong response.
* **Atomicity of key and effect.** The key record and the payment must be committed in the **same transaction**, or a crash between them either loses the guard or blocks a legitimate retry forever.
* **Expiry.** Keys must have a TTL (24-72 hours is typical). Keep them long enough to outlive every client retry policy, and prune with partitioning rather than row-by-row deletes.
* **Scope.** Keys should be scoped per API key or tenant, so one caller cannot collide with or probe another's keys.

### Where the idempotency layer belongs
As close to the entry point as possible — but it must share a transaction with the business effect, so a separate gateway-level cache is not sufficient on its own. A common design is a filter that manages the key record within the same datasource transaction as the handler.

### Also worth saying
* Make operations **naturally idempotent** where you can: \`PUT\` with a client-supplied id beats \`POST\` that allocates one.
* Downstream calls need the same treatment — propagate a derived idempotency key to the payment processor, or you have merely moved the problem.
* Retries must use **exponential backoff with jitter**, and only for retryable failures. Retrying a 400 forever is a self-inflicted outage.`,
    codeSnippet: `-- The unique constraint is the concurrency control
CREATE TABLE idempotency (
    key         text PRIMARY KEY,
    tenant_id   uuid NOT NULL,
    request_hash text NOT NULL,
    status      text NOT NULL,           -- IN_PROGRESS | COMPLETED
    response    jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);

@Transactional
public ResponseEntity<Receipt> charge(String key, ChargeRequest req) {
    var existing = repo.find(key);
    if (existing.isPresent()) {
        if (!existing.get().requestHash().equals(hash(req)))
            return status(422).build();                       // key reused, different body
        if (existing.get().isInProgress())
            return status(409).header("Retry-After", "1").build();
        return ok(existing.get().response());                 // replay stored result
    }
    repo.insertInProgress(key, hash(req));   // unique constraint serialises retries
    Receipt r = processor.charge(req);       // same transaction as the key record
    repo.complete(key, r);
    return ok(r);
}`,
    pitfalls: [
      'Letting the server generate the idempotency key.',
      'Returning success for an in-progress request instead of 409.',
      'Committing the key record and the business effect in separate transactions.',
      'Not detecting key reuse with a different request body.'
    ],
    followUpQuestions: [
      'How do you propagate idempotency to downstream payment processors?',
      'What TTL would you choose and how do you prune the table efficiently?',
      'How does this interact with the outbox pattern for emitting a PaymentCompleted event?'
    ],
    faangFocus: 'A standard payments-domain design question at Stripe, Adyen and similar. The in-progress and key-reuse edge cases are what separate a real design from a sketch.'
  },
  {
    id: 'arch-6',
    categoryId: 'architecture',
    title: 'CAP, PACELC and What Consistency Actually Means',
    difficulty: 'Hard',
    tags: ['CAP', 'PACELC', 'Consistency', 'Distributed Systems'],
    scenario: 'A design review claims the new service is "AP with eventual consistency" and therefore "always available". A reviewer asks what happens to a user who writes then immediately reads.',
    question: 'State CAP precisely, explain why the common formulation is misleading, and describe the consistency models that actually matter in design.',
    idealAnswer: `### CAP, stated precisely
For a distributed system experiencing a **network partition**, you must choose between **Consistency** (linearizability) and **Availability** (every non-failing node answers). That is it.

### Why "pick two of three" is misleading
* Partitions are **not a choice** — they happen. So the real decision is only what to do *during* one, which makes "CA" meaningless for a distributed system.
* "Consistency" in CAP means **linearizability** specifically, not the C in ACID. Conflating the two is the single most common error.
* "Availability" means **every** node responds, which is stricter than "the system has high uptime". A system that fails 0.001% of requests during a partition is not CAP-available but is operationally excellent.
* Partitions are rare. Most of the time the system is not partitioned, and CAP says nothing about that case — which is where almost all real latency lives.

### PACELC — the more useful framing
**If Partitioned, choose A or C; Else, choose L (latency) or C.**

This captures the trade-off you actually make every day: synchronous cross-region replication buys consistency and costs latency; asynchronous replication buys latency and costs consistency. DynamoDB is PA/EL, a strongly-consistent Spanner-style system is PC/EC.

### Answering the reviewer's question
"Eventual consistency" says only that replicas converge **eventually**, with no bound. So yes — a user can write and then read a stale value from another replica. That is often unacceptable for the user's *own* data.

The fix is a stronger model targeted at the case that matters:
* **Read-your-writes** — a session sees its own updates. Implement by routing a session to the same replica for a window, or by passing a write timestamp/token the read waits for.
* **Monotonic reads** — a session never sees time go backwards.
* **Causal consistency** — operations that are causally related are seen in order by everyone. Strong enough for most collaborative applications and achievable without global coordination.
* **Linearizable** — behaves like a single copy. Requires consensus (Raft/Paxos), so it costs a round trip and is unavailable during partitions.

### The design guidance
Choose consistency **per operation**, not per system. A single product can have linearizable account balances, causally-consistent comments, and eventually-consistent view counters. Blanket labels like "we're AP" hide the fact that different data has different requirements.

And state the **conflict resolution** strategy explicitly: last-write-wins silently loses data; version vectors detect conflicts; CRDTs converge deterministically without coordination. "Eventually consistent" with no stated resolution rule is an unfinished design.`,
    codeSnippet: `// Read-your-writes: carry the write position and route reads accordingly
record WriteToken(long lsn, String shard) { }

WriteToken write(Order o) {
    long lsn = primary.write(o);
    return new WriteToken(lsn, shard(o));        // return to the client
}

Order read(String id, WriteToken token) {
    Replica r = pickReplica(token.shard());
    if (r.appliedLsn() < token.lsn()) r = primary;   // fall back rather than serve stale
    return r.read(id);
}`,
    pitfalls: [
      'Treating CAP\'s C as ACID\'s C.',
      'Claiming a system is "CA".',
      'Saying "eventually consistent" without specifying a conflict resolution strategy.',
      'Applying one consistency model to all data in a product.'
    ],
    followUpQuestions: [
      'How do CRDTs converge without coordination, and what do they cost?',
      'What is the latency cost of linearizable reads in a Raft-based system?',
      'How would you implement monotonic reads across a fleet of replicas?'
    ],
    faangFocus: 'A standard distributed-systems screen. Correcting the "pick two" framing and reaching for PACELC immediately marks a strong candidate.'
  },
  {
    id: 'arch-7',
    categoryId: 'architecture',
    title: 'Kafka Consumer Groups, Ordering and Rebalancing',
    difficulty: 'Hard',
    tags: ['Kafka', 'Partitions', 'Rebalance', 'Ordering'],
    scenario: 'An order-processing consumer group loses its partitions every few minutes ("rebalance storm"), duplicates messages after each rebalance, and occasionally processes two events for the same order out of order.',
    question: 'Explain Kafka\'s partition and consumer group model, diagnose all three symptoms, and describe the correct configuration.',
    idealAnswer: `### The model
A topic is split into **partitions**. Ordering is guaranteed **within a partition only** — never across a topic. Each partition is assigned to **exactly one consumer** in a group, so parallelism is capped at the partition count. Producers choose the partition by key hash, so **all events for the same key land in the same partition** and are therefore ordered.

### Symptom 1: rebalance storms
A rebalance is triggered when the group's membership changes. The usual cause is a consumer being **considered dead**:
* \`max.poll.interval.ms\` exceeded — processing a batch took longer than the allowed gap between \`poll()\` calls. This is by far the most common cause.
* \`session.timeout.ms\` exceeded with no heartbeat (heartbeats are sent on a background thread since 0.10.1, so this usually indicates a real problem).

**Fixes:** reduce \`max.poll.records\` so a batch is quick, raise \`max.poll.interval.ms\` to a realistic bound, move slow work off the poll thread with your own bounded executor and pause/resume the partitions, and use **cooperative sticky assignment** (\`CooperativeStickyAssignor\`) so a rebalance no longer stops the world — only the moved partitions pause. Static group membership (\`group.instance.id\`) avoids rebalances entirely for routine restarts.

### Symptom 2: duplicates after rebalance
Offsets are committed **periodically** with \`enable.auto.commit\`. On rebalance, everything processed since the last commit is redelivered to the new owner.

**Fixes:** disable auto-commit and commit **after** processing, and — because at-least-once is the only realistic guarantee — make consumers **idempotent**. A processed-message table keyed by (topic, partition, offset) or by a business event id, checked in the same transaction as the side effect, is the standard approach. Kafka transactions give exactly-once *within* Kafka (read-process-write), but not across an external database.

### Symptom 3: out-of-order events for one order
This means events for the same order landed in **different partitions**. Either the producer did not set a key, or the key is not the order id, or the partition count changed (which re-maps hashes). It can also happen if a consumer processes a batch **concurrently** across threads without preserving per-key order.

**Fixes:** key by order id, never change partition count on a keyed topic without a migration plan, and if you parallelise consumption, shard the work **by key** so each key stays on one thread.

### The configuration that matters
Also set \`acks=all\` and \`enable.idempotence=true\` on the producer to prevent duplicates and reordering caused by producer retries — \`max.in.flight.requests.per.connection > 1\` without idempotence can reorder on retry.

### Operations
Monitor **consumer lag** per partition as the primary health signal, alert on rebalance frequency, and give poison messages a dead-letter topic with a retry limit — a single unprocessable message must not block a partition forever.`,
    codeSnippet: `# Consumer: no auto-commit, small batches, cooperative rebalancing
enable.auto.commit=false
max.poll.records=100
max.poll.interval.ms=300000
partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor
group.instance.id=orders-consumer-3        # static membership: no rebalance on restart

# Producer: no duplicates, no reordering on retry
acks=all
enable.idempotence=true

// Key by order id => same partition => ordered
producer.send(new ProducerRecord<>("orders", order.id(), event));`,
    pitfalls: [
      'Expecting global ordering across a topic.',
      'Leaving auto-commit on and being surprised by duplicates.',
      'Doing slow work on the poll thread and triggering max.poll.interval rebalances.',
      'Parallelising consumption without sharding by key, destroying per-key ordering.'
    ],
    followUpQuestions: [
      'How does cooperative rebalancing differ from eager, and what does it cost?',
      'What exactly does Kafka\'s exactly-once semantics cover, and what does it not?',
      'How do you safely increase the partition count of a keyed topic?'
    ],
    faangFocus: 'A staple at event-driven companies. Diagnosing "out of order" as a partitioning-key problem rather than a Kafka problem is the key insight.'
  },
  {
    id: 'arch-8',
    categoryId: 'architecture',
    title: 'API Versioning and Backward Compatibility',
    difficulty: 'Solid',
    tags: ['API Design', 'Versioning', 'Compatibility', 'Deprecation'],
    scenario: 'A public API must rename a field, change a date format, and split one endpoint into two. There are 400 external integrators, some of whom will never update.',
    question: 'Design a versioning and deprecation strategy. Explain what counts as a breaking change and how to evolve without a big-bang migration.',
    idealAnswer: `### What is actually breaking
**Non-breaking (additive):**
* Adding an optional request field with a sensible default.
* Adding a response field — *provided* clients ignore unknown fields. Say this explicitly in your API contract; it is the single most valuable rule you can establish early.
* Adding a new endpoint or a new enum value **that clients are told to tolerate**.

**Breaking:**
* Renaming or removing a field, or narrowing a type.
* Changing a format (this date change is breaking even though the field name is unchanged).
* Making an optional field required, or tightening validation.
* Changing status codes or error semantics.
* Adding an enum value **if** clients switch exhaustively on it — which is why tolerance must be documented up front.

### Versioning strategies
* **URI path (\`/v1/orders\`)** — visible, cacheable, trivially routable. Ugly by REST purism, but overwhelmingly the most practical for public APIs, and what most large providers use.
* **Header / content negotiation (\`Accept: application/vnd.acme.v2+json\`)** — cleaner URIs, but harder to test, harder to cache, and easy for clients to get wrong.
* **Query parameter** — simple, but easily lost in proxies and logs.

Version the **API**, not each endpoint — per-endpoint versions produce a combinatorial matrix nobody can reason about. Keep major versions few (v1, v2) and evolve additively within them.

### Evolving without a big bang
This is the same **expand-contract** idea as database migration:
1. **Expand** — add \`username\` alongside \`usr_nm\`, and the new ISO-8601 date field alongside the old format. Populate both.
2. **Communicate** — deprecate the old fields with a \`Deprecation\` and \`Sunset\` header (RFC 8594), documentation, and direct outreach.
3. **Measure** — instrument per-field and per-client usage. You cannot remove what you cannot prove is unused; this telemetry is what makes the final step possible.
4. **Contract** — remove only after usage reaches zero or the announced sunset date passes.

For the endpoint split, keep the old endpoint as a **facade** delegating to the new ones. Integrators migrate at their own pace.

### The 400-integrator reality
* Give a **long, explicit support window** (12+ months for a public API) and publish the policy so it is not negotiated per client.
* Never break within a major version. Ever. Trust is the product.
* Consider a **compatibility layer** at the edge (a gateway transform) so old shapes are served without the core carrying legacy code forever.
* Offer a sandbox and a migration guide with diffs, and consider migrating high-value clients by hand.

### For event schemas
The same discipline, enforced by a **schema registry** with compatibility checks (BACKWARD/FORWARD/FULL). Avro and Protobuf make additive evolution safe if you follow the rules: never reuse a field number, never change a type, always default new fields.`,
    codeSnippet: `# Signal deprecation in-band (RFC 8594) so clients can act automatically
HTTP/1.1 200 OK
Deprecation: Sun, 01 Jun 2026 00:00:00 GMT
Sunset: Tue, 01 Dec 2026 00:00:00 GMT
Link: <https://docs.acme.com/migrate/v2>; rel="deprecation"

{
  "usr_nm": "debu",                       // legacy, still populated
  "username": "debu",                     // new
  "created": "2026-08-21",                // legacy format
  "createdAt": "2026-08-21T09:14:00Z"     // new ISO-8601
}`,
    pitfalls: [
      'Breaking a field within an existing major version.',
      'Versioning individual endpoints and creating an unmanageable matrix.',
      'Removing a deprecated field without per-client usage telemetry.',
      'Assuming adding an enum value is safe when clients switch exhaustively.'
    ],
    followUpQuestions: [
      'How would you instrument per-field usage across 400 integrators?',
      'What compatibility mode would you set in a schema registry, and why?',
      'When is a gateway-level compatibility shim better than versioned code in the service?'
    ],
    faangFocus: 'API-platform interviews. The additive expand-contract approach plus usage telemetry before removal is the answer that shows you have retired an API for real.'
  },
  {
    id: 'arch-9',
    categoryId: 'architecture',
    title: 'When Not to Use Microservices',
    difficulty: 'Hard',
    tags: ['Microservices', 'Modular Monolith', 'Coupling', 'Architecture'],
    scenario: 'A 12-person team maintains 30 microservices. A single feature typically requires changes to 5 of them, deployments must be coordinated, and local development needs Docker Compose with 18 containers.',
    question: 'Diagnose the architecture. Explain what microservices actually buy, what they cost, and what you would do here.',
    idealAnswer: `### The diagnosis: a distributed monolith
The symptoms are definitive:
* A feature touching 5 services means the **service boundaries do not match the change boundaries**. Boundaries should follow how the system changes, not how the domain diagram looks.
* Coordinated deployment means the **independent deployability** — the primary benefit of microservices — was never actually achieved.
* 30 services for 12 people is roughly 2.5 services per engineer. Each carries a pipeline, dashboards, alerts, dependencies and on-call surface.

This is the worst of both worlds: the coupling of a monolith plus the operational cost and failure modes of a distributed system.

### What microservices genuinely buy
* **Independent deployability** — teams ship without coordination. This is the whole point; everything else is secondary.
* **Independent scaling** of components with genuinely different load profiles.
* **Fault isolation**, if boundaries are drawn well and calls are properly insulated.
* **Technology heterogeneity**, which is rarely as valuable as it sounds.
* **Organisational scaling** — Conway's Law, deliberately applied. Microservices are primarily an *organisational* solution.

### What they cost
* Every in-process call becomes a network call: latency, partial failure, retries, timeouts, serialisation.
* Distributed data — no cross-service transactions, so sagas, eventual consistency and idempotency everywhere.
* Distributed debugging: you need tracing, correlation ids and log aggregation before you can operate at all.
* Multiplied operational surface: pipelines, dashboards, alerting, secrets, certificates, on-call rotation per service.
* Local development complexity — 18 containers is a productivity tax paid every single day.

The rule of thumb worth stating: **microservices trade in-process complexity for operational complexity.** That is a good trade when the constraint is *organisational* (too many people on one codebase) and a bad trade when the constraint is *technical*.

### What I would do here
**Consolidate towards a modular monolith**, keeping only the services with a genuine independent reason to exist.
1. Map which services change together — Git history is the evidence. Services that always change together should be merged.
2. Merge them into modules within one deployable, with **enforced boundaries**: package structure, no cross-module imports except through published interfaces, and ArchUnit tests to enforce it in CI.
3. Communicate between modules with in-process events, so the seams stay explicit and extractable later.
4. Keep separate services only where there is a real independent scaling profile, a different availability requirement, or a genuinely separate team.

A well-modularised monolith gives you fast local development, real transactions, refactoring across boundaries, and one deployment — while preserving the option to extract a module later, when a **specific** reason appears.

### The framing to state explicitly
Start with a modular monolith. Extract a service when you have a concrete reason: an independent scaling need, an independent team, or an independent availability requirement. **Do not extract on speculation** — a boundary drawn before you understand the domain is very expensive to move.`,
    codeSnippet: `// Enforce module boundaries in a monolith so it does not rot into a big ball of mud
@AnalyzeClasses(packages = "com.acme")
class ArchitectureTest {

    @ArchTest
    static final ArchRule modulesDoNotDependOnInternals =
        noClasses().that().resideInAPackage("..orders..")
            .should().dependOnClassesThat()
            .resideInAPackage("..billing.internal..");

    @ArchTest
    static final ArchRule noCycles =
        slices().matching("com.acme.(*)..").should().beFreeOfCycles();
}`,
    pitfalls: [
      'Treating microservices as a technical default rather than an organisational solution.',
      'Extracting services before the domain boundaries are understood.',
      'Claiming independent deployability while every feature requires coordinated releases.',
      'Ignoring the daily developer-productivity cost of a large local environment.'
    ],
    followUpQuestions: [
      'How would you use commit history to identify services that should be merged?',
      'What concrete signals justify extracting a module into a service?',
      'How do you keep a modular monolith from degrading back into a big ball of mud?'
    ],
    faangFocus: 'A senior/staff judgement question. Willingness to recommend consolidation — and to define the specific triggers for extraction — is exactly what interviewers look for.'
  },
  {
    id: 'arch-10',
    categoryId: 'architecture',
    title: 'Designing a Rate-Limited, Multi-Region Read Path',
    difficulty: 'Expert',
    tags: ['Multi-Region', 'Replication', 'Latency', 'Failover'],
    scenario: 'A product catalogue must serve 200,000 reads/second globally at p99 under 50ms, with writes concentrated in one region. Occasional regional failures must not take the read path down.',
    question: 'Design the read path end to end. Cover replication, caching tiers, consistency, and failover.',
    idealAnswer: `### Start from the constraint
Physics sets the floor: a cross-Atlantic round trip is ~70-90ms. A 50ms global p99 therefore **requires serving reads from within the user's region** — no amount of optimisation makes a cross-region read fit the budget. That single observation drives the whole design.

### The tiers, outermost first
1. **CDN / edge cache.** Catalogue data is read-mostly and mostly public — ideal for edge caching. Use \`Cache-Control\` with a modest TTL plus \`stale-while-revalidate\` so expiry never causes a latency cliff. This absorbs the large majority of the 200k/s before it reaches any service.
2. **Regional read replicas.** Asynchronous replication from the write region. Each region serves its own reads. Replication lag is the consistency cost, and must be **measured and exported as a metric**, not assumed.
3. **Regional cache (Redis) + in-process cache (Caffeine).** The local tier removes network hops entirely for the hottest items; it also protects against a Redis outage. Keep local TTLs short — the price of a second cache tier is a second staleness window.
4. **Origin** — the regional replica, then the primary as a last resort.

### Consistency
Be explicit about what the design gives:
* Global reads are **eventually consistent**, bounded by replication lag plus cache TTL. State the number: "reads may be up to N seconds stale".
* For a writer reading their own change, use **read-your-writes**: after a write, pin that session to the primary (or to a replica that has caught up) for a short window, or serve from a write-through cache.
* Invalidate on write by **publishing an invalidation event** to every region rather than relying on TTL alone. Cache-key versioning (including a content version in the key) makes invalidation a no-op — the new key simply misses.

### Failover
* **Reads:** DNS or anycast with health checks routes traffic away from a failed region. Because every region is a full read path, losing one is a capacity event rather than an outage. Provision headroom for N-1.
* **Writes:** a single write region means a regional failure requires **promoting a replica**. Decide in advance whether that is automatic (fast, risk of split-brain) or manual (slower, safer), and practise it. Document the RPO — with asynchronous replication, a failover **can lose recent writes**, and that must be an accepted, stated trade-off.
* **Guard against correlated failure:** a regional outage shifts its traffic elsewhere. If the remaining regions are sized at exactly 100%, the failover causes the second outage.

### Protecting the origin
* **Request coalescing / single-flight** per key so a cache miss storm cannot become an origin stampede.
* **TTL jitter** so a key population does not expire simultaneously.
* **Load shedding** at the edge with a clear priority order, and rate limits per client.
* **Negative caching** for missing ids.

### Verification
Synthetic probes per region measuring true p99, exported replication lag, cache hit ratios per tier, and **regular failover drills**. A failover path that has never been exercised does not work.`,
    codeSnippet: `# Edge: absorb the bulk of traffic, never let expiry cause a latency cliff
Cache-Control: public, max-age=60, stale-while-revalidate=300, stale-if-error=86400

// Local tier with single-flight so a miss storm cannot reach the origin
LoadingCache<String, Product> local = Caffeine.newBuilder()
        .maximumSize(50_000)
        .expireAfterWrite(Duration.ofSeconds(30 + jitter()))
        .refreshAfterWrite(Duration.ofSeconds(20))     // serve stale, refresh behind
        .recordStats()
        .build(id -> regionalCache.get(id, () -> replica.load(id)));

// Read-your-writes: pin the session to the primary briefly after a write
if (session.wroteWithin(Duration.ofSeconds(5))) return primary.load(id);`,
    pitfalls: [
      'Serving cross-region reads and missing the latency budget on physics alone.',
      'Relying on TTL expiry alone for invalidation.',
      'Sizing regions with no N-1 headroom, so a failover causes a second outage.',
      'Never practising the write-region failover and not stating the RPO.'
    ],
    followUpQuestions: [
      'How would you bound and monitor replication lag, and what do you do when it spikes?',
      'What are the risks of automatic write-region promotion, and how do you avoid split-brain?',
      'How does cache-key versioning remove the need for explicit invalidation?'
    ],
    faangFocus: 'A staff-level system design round. Opening with the speed-of-light constraint immediately frames the problem correctly and impresses interviewers.'
  },
  {
    id: 'arch-11',
    categoryId: 'architecture',
    title: 'Distributed Tracing and Debugging Across Services',
    difficulty: 'Hard',
    tags: ['Tracing', 'OpenTelemetry', 'Observability', 'Correlation'],
    scenario: 'A user reports that checkout occasionally takes 12 seconds. The request crosses 9 services. Each service has logs and dashboards, but nobody can find where the time went.',
    question: 'Explain distributed tracing: the data model, context propagation, sampling, and how it combines with logs and metrics.',
    idealAnswer: `### The data model
* A **trace** is one end-to-end request, identified by a \`trace_id\`.
* A **span** is one unit of work — an HTTP handler, a database query, a message consume — with a \`span_id\`, a **parent span id**, a start time, a duration, a status, and attributes.
* Spans form a **tree**, so a waterfall view shows exactly where the 12 seconds went: which span was long, and whether it was self-time or waiting on a child.

That waterfall is the answer to this scenario. Logs tell you what happened in one service; a trace tells you the shape of the whole request.

### Context propagation
The \`trace_id\` and current \`span_id\` must travel with the request. The standard is **W3C Trace Context** (\`traceparent\` and \`tracestate\` headers), which replaced vendor-specific formats like B3.

Propagation must cover **every** boundary:
* HTTP — headers, injected and extracted by instrumentation.
* Messaging — Kafka/RabbitMQ **message headers**, not the payload. This is the boundary most often missed, and it is why traces so often stop at the first async hop.
* Thread boundaries — a task handed to an executor loses ThreadLocal-based context unless you decorate it.
* Scheduled and batch work — start a new trace and **link** it to the originating one.

### Sampling
At scale you cannot store every trace.
* **Head-based** — decide at the first service (e.g. 1%). Cheap and simple, but you will usually miss the rare 12-second request, which is exactly the one you need.
* **Tail-based** — buffer spans at a collector and decide **after** seeing the whole trace, keeping all errors and all slow traces. Far more useful for this problem; costs collector memory and complexity.
* **Always sample errors**, and support a per-request debug flag so support can force capture for a specific user.

The lesson: head sampling optimises for cost, tail sampling optimises for debuggability. For latency investigation you want tail-based.

### The three signals together
* **Metrics** tell you *that* something is wrong (RED/USE, with percentiles).
* **Traces** tell you *where*.
* **Logs** tell you *why*.

They must be linked: put \`trace_id\` in every log line (via MDC), and use **exemplars** on latency histograms so a spike in a dashboard links directly to a representative trace. Without that linkage you still end up grepping nine services by hand.

### Practical guidance
* Use **OpenTelemetry** — vendor-neutral, auto-instrumentation for Spring/JDBC/Kafka via a Java agent, so most spans arrive with no code changes.
* Add **semantic-convention attributes** (\`http.route\`, \`db.statement\`, \`messaging.system\`) so tooling can aggregate. Avoid unbounded-cardinality attributes.
* Record **span events** for retries, cache misses and circuit-breaker trips.
* Trace context also carries **baggage** (tenant, feature flags) — useful, but it travels over the wire, so never put anything sensitive in it.

### For the 12-second checkout specifically
Tail-based sampling keeping all traces over 5 seconds, plus exemplars from the p99 latency histogram, would surface the offending trace within minutes — and the waterfall would name the span.`,
    codeSnippet: `// Put trace context in every log line so logs and traces join up
@Bean Filter mdcFilter() {
    return (req, res, chain) -> {
        SpanContext ctx = Span.current().getSpanContext();
        MDC.put("traceId", ctx.getTraceId());
        MDC.put("spanId", ctx.getSpanId());
        try { chain.doFilter(req, res); } finally { MDC.clear(); }
    };
}

// Propagate across a message boundary — the hop most often missed
propagator.inject(Context.current(), record.headers(),
        (headers, key, value) -> headers.add(key, value.getBytes(UTF_8)));

# Tail sampling: keep every error and every slow trace
processors: [tail_sampling: { policies: [{ type: status_code, status: ERROR },
                                         { type: latency, threshold_ms: 5000 }] }]`,
    pitfalls: [
      'Head-based sampling at 1%, guaranteeing you miss the rare slow request.',
      'Losing trace context across message queues or executor boundaries.',
      'Not putting trace_id in logs, so the three signals cannot be joined.',
      'Putting sensitive data in baggage, which crosses service boundaries.'
    ],
    followUpQuestions: [
      'What are exemplars and how do they link a metric spike to a trace?',
      'How do you trace a request that fans out asynchronously and rejoins later?',
      'What is the overhead of OpenTelemetry auto-instrumentation, and how do you bound it?'
    ],
    faangFocus: 'An observability round staple. Naming tail-based sampling as the fix for "we never capture the slow request" is the detail that lands.'
  },
  {
    id: 'arch-12',
    categoryId: 'architecture',
    title: 'Designing for Graceful Degradation',
    difficulty: 'Expert',
    tags: ['Degradation', 'Load Shedding', 'SLO', 'Resilience'],
    scenario: 'During a traffic surge the homepage fails entirely because the personalisation service is overloaded, even though 95% of the page is static content that does not depend on it.',
    question: 'Explain graceful degradation as a design discipline. Cover criticality tiers, load shedding, timeouts and how you would restructure this page.',
    idealAnswer: `### The core failure
The page treats every dependency as **mandatory**. One non-essential service being slow makes the whole page unavailable. Availability is being computed as the **product** of all dependencies' availabilities — with 9 dependencies at 99.9%, the theoretical ceiling is already 99.1%.

Graceful degradation breaks that multiplication by making most dependencies optional.

### Criticality tiers
Classify every dependency explicitly at design time:
* **Critical** — the feature is meaningless without it (product data on a product page). Failure here is a real failure.
* **Important** — degrades quality but not function (pricing personalisation, inventory counts). Serve a default or a cached value.
* **Optional** — enhancement only (recommendations, recently-viewed, banners). Omit silently.

This classification must be written down and **reviewed**, because the default engineering instinct is to treat everything as critical.

### Restructuring the homepage
1. **Render the static shell first** from data the page always has.
2. Fetch personalisation with an **aggressive timeout** — 100-200ms, not the service's own SLO. If it misses, render the generic version. The user gets a slightly less personal page instead of an error.
3. Serve **stale personalisation** from cache when the service is down (\`stale-if-error\`). Yesterday's recommendations are far better than a 500.
4. Wrap each optional dependency in a **circuit breaker with a fallback**, so a sustained outage stops even attempting the call.
5. Consider **client-side hydration** for optional blocks, so their failure cannot affect the server-rendered response at all.

### Load shedding
When you cannot serve everything, choose deliberately what to drop:
* **Prioritise by request class** — checkout above browsing, paying customers above anonymous crawlers, human traffic above bots.
* Shed at the **edge**, cheaply, before the request consumes backend resources.
* Prefer shedding a **fraction of requests fully** over serving everything slowly: uniform slowness triggers client retries and makes overload worse. Fast rejection with \`Retry-After\` is kinder than a timeout.
* Adaptive concurrency limits (Netflix's concurrency-limits, or a TCP-Vegas-style gradient algorithm) find the right limit automatically instead of relying on a static guess.

### Timeouts as a budget
Assign a **latency budget** for the whole request and give each dependency a slice. A downstream timeout must always be **shorter** than the caller's remaining budget, or the caller times out first and the work is wasted. Propagate the remaining deadline in a header so downstream services can shed work they cannot finish in time.

### Verify it
Degradation paths that are never exercised do not work. **Game days and fault injection** — kill the personalisation service in staging (and, when mature, in production) and confirm the page still renders. Alert on **fallback rate**, so silent degradation is visible rather than something you discover in a quarterly review.

### The framing
Design for **partial failure as the normal case**. Ask of every dependency: "what does the user see if this is down?" A design where the honest answer is "an error page" for an optional feature is not finished.`,
    codeSnippet: `// Optional dependency: short timeout, breaker, stale fallback, and a metric
@CircuitBreaker(name = "personalisation", fallbackMethod = "genericBlocks")
@TimeLimiter(name = "personalisation")           // 150ms, not the service's own SLO
CompletableFuture<List<Block>> personalised(User u) {
    return CompletableFuture.supplyAsync(() -> client.blocks(u));
}

CompletableFuture<List<Block>> genericBlocks(User u, Throwable t) {
    fallbackRate.increment("personalisation");   // silent degradation must be visible
    return completedFuture(staleCache.getOrDefault(u.id(), Blocks.GENERIC));
}

// Propagate the remaining deadline so downstream can shed work it cannot finish
headers.set("X-Request-Deadline", Instant.now().plusMillis(remainingBudget).toString());`,
    pitfalls: [
      'Treating every dependency as mandatory and multiplying availabilities.',
      'Using the downstream service\'s own SLO as your timeout.',
      'Serving everything slowly under overload instead of shedding a fraction quickly.',
      'Never testing the fallback paths, so they fail when finally needed.'
    ],
    followUpQuestions: [
      'How do you decide a timeout value from an end-to-end latency budget?',
      'How would you prioritise traffic classes when shedding load?',
      'How do adaptive concurrency limits beat a statically configured limit?'
    ],
    faangFocus: 'A staff-level resilience question. Criticality tiering plus "what does the user see if this is down?" is the framing interviewers remember.'
  },
];
